+++
<h1 align=center>
  <img src=./public/favicon-for-dark.svg#gh-dark-mode-only width=75>
  <img src=./public/favicon-for-light.svg#gh-light-mode-only width=75>
  <br>
  <span>
    Anxtgo
  </span>
</h1>
+++

Personality development in real life: Actively learn from experiences by reflecting and abstracting them into persistent knowledge. Make mistakes - but only once. Improve what's already working. It's possible through the power of experiential learning.


== The Project

=== What is experiential learning?

[quote, 'https://en.wikipedia.org/wiki/Experiential_learning[Wikipedia, the free encyclopedia]', Experiential learning]
Experiential learning is the process of learning through experience, and is more narrowly defined as "learning through reflection on doing".

// fix gh ugly spacing after adoc quotes by adding empty html block
+++
+++

Anxtgo implements the https://en.wikipedia.org/wiki/Kolb%27s_experiential_learning#The_experiential_learning_cycle[_experiential learning cycle_] by Kolb, which loops over the following stages:

. Concrete Experience
. Reflective Observation
. Abstract Conceptualization
. Active Experimentation

Since acting and experiencing fully take place in real life, these two steps are not integrated by Anxtgo directly, rather reflecting and abstracting are the core part of Anxtgo, due to the fact that these stages are processed by our brains mainly. Here, Anxtgo comes into play and wraps the whole cycle into a digital experience to help us go through it with ease and getting the most out of it.


=== Why experiential learning?

[quote, Kolb, 11984 HE]
Learning is the process whereby knowledge is created through the transformation of experience.

// fix gh ugly spacing after adoc quotes by adding empty html block
+++
+++

While the learning cycle can be kicked off at any stage, it's probably the most efficient to start on experiencing.

If there is something positive or negative in a given experience, we faced it and therefore see the point directly. At this point, we are no longer talking about some theoretical thing anymore, it's something we are experiencing and reflecting on for real.

Once we abstracted what we want to learn from the situation, it's a lot easier for us to remember our abstraction next time we enter a similar situation, because we linked that knowledge to an experience in our life. That's a natural human-like way to save information in our brains. Because of that, it's a also lot easier for us to build up persistent knowledge and actively bring our abstractions into real actions in our lifes.


=== Why Anxtgo?

* Write reflections and abstractions in one single flow designed for effective experiential learning. Or write down your reflection and come back later to abstract on the reflection. Make use of every experience, never miss something to learn from.
* Filter your personal list of reflections to quickly see what reflections you already have turned into abstractions and which you still have to get your head around.
* Connect new reflections to existing abstractions to build up your own network of knowledge and get a detailed history view, of when you made which reflections, that led or tries to implement your abstractions.
* Mark your reflections as implementations of your abstraction to generate a rating for each of your abstractions. This helps you see whether you are taking an abstraction into real life with success. Also you are able to sort all of your abstractions based on your scoring, to see what you should focus on and what you are doing great already.
* Get a statistical overview of all your entries to see the bigger picture of your experiences:
** Amount of already abstracted reflections (reflections linked to an abstraction)
** Amount of not yet abstracted reflections (reflections with no linked abstraction)
** Amount of reflections that implement their abstraction (successful)
** Amount of reflections that do not implement their abstraction (unsuccessful)
** Amount of not yet rated reflections (reflections where implements or not implements abstraction is not set)
// ** Get to know your average learning type, do you have more learning paths kicked off by a reflection or by an abstraction?
// ** Your avergae number of not abstraction implemented reflections per abstraction before your first implementation.


== Development

Anxtgo is build with https://vuejs.org[Vue.js], https://quasar.dev[Quasar] and https://dexie.org[Dexie.js].


=== https://www.anaconda.com/[Anaconda]

[source,zsh]
----
conda env create -n anxtgo --file environment.yml
conda activate anxtgo
----

[source,zsh]
----
conda env export > environment.yml
----


=== https://www.npmjs.com/[NPM]

[source,zsh]
----
npm install
----


=== https://quasar.dev/[Quasar]

[source,zsh]
----
quasar dev
----
